### ISSUE TITLE
Weird stroke scaling

### ISSUE THREAD

**Issue by Fatflo** [memononen/nanovg#279]
Hi,
I'm applying scaling on the x axis only, but it looks like the stokes are scaled up on both x and y. However when scaling down, there seem to be a minimum stroke width whatever the down scaling factor applied.
Are these phenomenons expected ?

Thanks,
Florian

**Comment by memononen** [comment]
The strokes are always drawn uniformly, because it simplifies the drawing the stroke anti-aliasing a lot.
Average of x and y scale is used to scale the stroke, see here:
https://github.com/memononen/nanovg/blob/master/src/nanovg.c#L2122

When the stroke becomes less than 1px wide, then it is faded out.

**Comment by Fatflo** [comment]
Hi Mikko,
ok thanks this explains what I observe here, in fact I tried ytsedan repository for the displaylist feature and I saw that he managed this differently: in his implementation the strokes can be scaled differently on x and y, that's why I saw a difference in my appli.
By the way, the displaylist feature accelerates my appli a lot ! (analog/digital trace viewer) do you have any plan for integrating such feature soon ?

**Comment by memononen** [comment]
Ah, I see. I dont have plans at this time integrating the displaylist feature. I do agree that it is important feature, just don't have the time to think it through and integrate.
