### ISSUE TITLE
nanovg antialiasing artifacts

### ISSUE THREAD

**Issue by AndreyArsov** [memononen/nanovg#415]
Can anyone shed light on the antialiasing model used by nanovg?
Specifically in the attached picture there is a comparison of path rendering between skia and nanovg (both using opengl). These are paths from glyphs of the string "Wall".
Both look good and pretty similar, but the nanovg one there is one lighter pixel at the bottom of the "W".
On screens with low DPI it looks very out of place.
This happens at specific sub-pixel positions, not always.

![anti-alias-cmp](https://user-images.githubusercontent.com/9951845/30923877-f66f467e-a361-11e7-9add-b135703f10c7.png)

**Comment by memononen** [comment]
Are you using font rendering, or do you draw the shapes as paths?

NanoVG uses stb_truetype for font rasterization, and the glyphs are stored in texture and drawn as quads on screen.

For path rendering, the paths are shrunken by 0.5 px and 1px wide "feather" is drawn around the paths. While it works most of the time, it does not handle well cases where you have more than one path affecting one pixel. The problem is that the coverage for that pixel is not accumulated correctly.

**Comment by AndreyArsov** [comment]
I need to use path since I don't have access to the font file, just paths for the glyphs. Agree though that using glyph bitmaps would be more efficient.

Is this coverage calculated in a shader or on the cpu?

Sorry, I haven't had time to go deeper in the path rendering implementation, but it sounds that this would not be easy to fix, is that correct?

Another way would be to draw the paths at higher resolution and then filter down. Essentially font atlas, but generating the bitmaps from paths, but not from the truetype files.

**Comment by memononen** [comment]
The coverage is calculated on software. Here's some pictures which might make it easier to understand: http://jet.ro/2011/06/04/better-looking-anti-aliased-lines-with-simple-trick/

But for filled shapes, we first need to inset the path by 0.5px and then add the 1px gradient, so that the shapes will not get thicker. Actually, the problem you're seeing can come from the path inset.

You can also use nanovg with MSAA, in that case the problem does not exists.

**Comment by AndreyArsov** [comment]
Yes, MSAA seems to work in this case. Does anyone know whether this is supported in WebGL? Eventually I would like to use emscripted to compile to JavaScript.
In this way one can have the same code for native and web platforms.

**Comment by lieff** [comment]
At least `glfwWindowHint(GLFW_SAMPLES, 8);` do not works with emscripten. I do not know how to resolve it either.

**Comment by memononen** [comment]
In WebGL you can initialize the context (`getContext´) with AA support, see WebGLContextAttributes.

**Comment by AndreyArsov** [comment]
Thanks, Mikko, will check it out.

**Comment by werame** [comment]
> NanoVG uses stb_truetype for font rasterization, and the glyphs are stored in texture and drawn as quads on screen.

Well, stb does (CPU-based) supersampling AA to some extent, but it seems to be [off by default](https://github.com/memononen/nanovg/blob/master/src/stb_truetype.h#L631) in stb. I'm not sure if nanovg is turning it on. Nanovg doesn't even seem to be calling that (packing) function in stb, which could do oversampling AA for the font. Stb (still) doesn't do hinting though, so at small font sizes (e.g 10 pts) would still not look that good.

> For path rendering, the paths are shrunken by 0.5 px and 1px wide "feather" is drawn around the paths. While it works most of the time, it does not handle well cases where you have more than one path affecting one pixel. The problem is that the coverage for that pixel is not accumulated correctly.

That's called analytic antialiasing in some corners. [Some](https://graphics.cs.illinois.edu/wp-content/uploads/2019/09/paper1013-main.pdf) have applied it to font rendering too. But it's quite a bit more involved than for simple paths.
