### ISSUE TITLE
Use nanovg in game dev

### ISSUE THREAD

**Issue by stillwarter** [memononen/nanovg#426]
Hi. I am happy to find this great lib. I am learning how to use it.
Is this lib suitable for 2d game graphic render and how?
Can I use opengl render together with nanovg?
thanks for your reply!

**Comment by olliwang** [comment]
For pure 2d game graphic, yes.

I use NanoVG to build [moui](https://github.com/ollix/moui) as a cross-platform development framework including a widget system purely written in NanoVG. And created a real-life game [Fog of World](https://fogofworld.com) (though unlike common video game), the UI is quite complicated as almost all UI components are rewritten in NanoVG instead of native iOS UIKit. So yes, NanoVG is powerful enough to do complex graphic jobs.

**Comment by stillwarter** [comment]
Great!
Do you know how to render a sprite or animation directly? There is ImagePattern in nanovg, but it looks not suitable for render a sprite.

**Comment by otoomey** [comment]
@stillwarter Nanovg allows you to render pictures/icons, draw paths and print text, you must do the animation yourself.

**Comment by stillwarter** [comment]
@otoomey just like this?
imgPaint := nanovgo.ImagePattern(tx+ix, ty+iy, iw, ih, 0.0/180.0*nanovgo.PI, imageID, 1.0)
ctx.BeginPath()
ctx.RoundedRect(tx, ty, thumb, thumb, 5)
ctx.SetFillPaint(imgPaint)
ctx.Fill()

**Comment by otoomey** [comment]
@stillwarter That's the general idea, yeah

**Comment by stillwarter** [comment]
@otoomey It looks like you have a better solution?
