### ISSUE TITLE
SDL_gpu + NanoVG Example

### ISSUE THREAD

**Issue by RandomErrorMessage** [memononen/nanovg#465]
I've created an example of SDL_gpu and NanoVG being used in combination, including using a NanoVG Frambuffer as a GPU_Image. Please let me know if there's any suggestions you have for my example code.
https://github.com/RandomErrorMessage/sdl-gpu/blob/nanovg/demos/nanovg/main.c

**Comment by memononen** [comment]
- If you call `nvgluCreateFramebuffer(_vg, _w, _h, NVG_IMAGE_NODELETE)` NanoVG will not delete the OpenGL image handle. Now it leaks memory.
- `GPU_ResetRendererState()` is needed after `nvgEndFrame()` because NanoVG changes the opengl state (i.e. binds textures, shaders, changed blend mode, etc)

The flip Y is needed because in OpenGL the origin is at bottom-left corner (the pixel that is at (0,0) texture coordinate), but images generally stored in top-left as origin. Nanovg and sdl_gpu both use the top-left image convention, so FBOs look upside down for them.
